FROM alpine:3.10
LABEL "com.github.actions.name"="PowerShell Actions Test"
LABEL "com.github.actions.description"="Move all PS function files into a single PSM1 file."
LABEL "com.github.actions.icon"="mic"
LABEL "com.github.actions.color"="purple"
LABEL "repository"="https://github.com/michaelsainz/GHAdmin"
LABEL "maintainer"="Michael Sainz <michaelsainz@github.com>"

RUN echo $PWD
